#!/bin/bash

run_dir="run"
bin_dir="run/bin"
test_dir="run/test"

function dir_exists {
  if [ $# -eq 0 ]; then
    echo "dir_exists requires a dir arg"
    exit 1
  fi

  dir=$1

  if [ ! -d $dir ]; then
    "run configure script before trying to build"
    exit 1
  fi
}

dir_exists $run_dir
dir_exists $bin_dir
dir_exists $test_dir

gcc -std=c99 -Wall -Wextra -lm src/*.c -o $bin_dir/rpg
gcc -std=c99 -Wall -Wextra -lm test/test_rand.c src/safer_rand.c -o $test_dir/test_rand
